# Stage 1: Build
FROM maven:3.8-openjdk-17-slim AS build
WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN ./mvnw dependency:go-offline
COPY src ./src
RUN ./mvnw clean package -DskipTests

# Stage 2: Run
FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/notification-service-0.0.1-SNAPSHOT.jar notification-service.jar
EXPOSE 8082

# Metadata (optional)
LABEL maintainer="your-name@domain.com"
LABEL description="Docker image for Notification Service"

ENTRYPOINT ["java", "-jar", "notification-service.jar"]